# Generated by Django 3.2.16 on 2023-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.CharField(default='Китай', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Бавовна', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='S', max_length=5),
        ),
    ]
